const data = [
  {
    severity: 'S2',
    note: 'Kindly update your Bugs by adding Aim and Important Links Section in Description i.e. comment#1.\n\nScreenshot -> https://screenshot.googleplex.com/84aaCCbfBQNnTCQ for reference.\n\nIgnore this if already Done.',
    mentor: '',
    project: 'Background Work - Production KT',
    reviewer: '',
    type: 'epic',
    title:
      '[Parent Tracking Bug][HEALTH][covid_19_nyt_stats] For production pipelines KT',
    priority: 'P2',
    secondary: '',
    projectStatus: 'In-Progress',
    eta: '',
    vfOrg: 'NO',
    id: '260062167',
    assignee: 'apurvsharma',
    otd: '',
    primary: '',
    status: 'ACCEPTED',
  },
  {
    severity: 'S2',
    note: 'Kindly update your Bugs by adding Aim and Important Links Section in Description i.e. comment#1.\n\nScreenshot -> https://screenshot.googleplex.com/84aaCCbfBQNnTCQ for reference.\n\nIgnore this if already Done.',
    mentor: '',
    project: 'Background Work - Production KT',
    reviewer: '',
    type: 'epic',
    title:
      '[Parent Tracking Bug][HEALTH][covid_19_nyt_stats] For production pipelines KT',
    priority: 'P2',
    secondary: '',
    projectStatus: 'In-Progress',
    eta: '',
    vfOrg: 'NO',
    assignee: 'apurvsharma',
    id: '260062167',
    otd: '',
    status: 'ACCEPTED',
    primary: 'apurvsharma',
  },
  {
    severity: 'S2',
    note: 'Kindly update your Bugs by adding Aim and Important Links Section in Description i.e. comment#1.\n\nScreenshot -> https://screenshot.googleplex.com/84aaCCbfBQNnTCQ for reference.\n\nIgnore this if already Done.',
    mentor: '',
    project: 'Background Work - Production KT',
    reviewer: '',
    type: 'epic',
    title:
      '[Parent Tracking Bug][HEALTH][covid_19_nyt_stats] For production pipelines KT',
    priority: 'P2',
    secondary: '',
    projectStatus: 'In-Progress',
    eta: '',
    vfOrg: 'NO',
    assignee: 'apurvsharma',
    id: '260062167',
    otd: '',
    status: 'ACCEPTED',
    primary: '',
  },
  {
    severity: 'S2',
    note: 'Kindly update your Bugs by adding Aim and Important Links Section in Description i.e. comment#1.\n\nScreenshot -> https://screenshot.googleplex.com/84aaCCbfBQNnTCQ for reference.\n\nIgnore this if already Done.',
    mentor: '',
    project: 'Background Work - Production KT',
    reviewer: 'sayyadz',
    title:
      '[Parent Tracking Bug][HEALTH][covid_19_nyt_stats] For production pipelines KT',
    priority: 'P2',
    type: 'epic',
    secondary: '',
    projectStatus: 'In-Progress',
    eta: '',
    vfOrg: 'NO',
    id: '260062167',
    assignee: 'apurvsharma',
    otd: '',
    status: 'ACCEPTED',
    primary: '',
  },
  {
    severity: 'S2',
    note: 'Kindly update your Bugs by adding Aim and Important Links Section in Description i.e. comment#1.\n\nScreenshot -> https://screenshot.googleplex.com/84aaCCbfBQNnTCQ for reference.\n\nIgnore this if already Done.',
    mentor: 'sayyadz',
    project: 'Background Work - Production KT',
    reviewer: '',
    priority: 'P2',
    title:
      '[Parent Tracking Bug][HEALTH][covid_19_nyt_stats] For production pipelines KT',
    type: 'epic',
    secondary: '',
    projectStatus: 'In-Progress',
    eta: '',
    vfOrg: 'NO',
    assignee: 'apurvsharma',
    id: '260062167',
    otd: '',
    primary: '',
    status: 'ACCEPTED',
  },
  {
    severity: 'S2',
    note: 'This is acknowledged.\n',
    mentor: '',
    project: 'Background Work - Production KT',
    reviewer: '',
    priority: 'P2',
    type: 'epic',
    title:
      '[Parent Tracking Bug][Search Features][daas_request_responsiveness] For production pipelines KT',
    secondary: '',
    projectStatus: 'In-Progress',
    eta: '1/31/2023',
    vfOrg: 'NO',
    id: '265219473',
    assignee: 'apurvsharma',
    otd: '1/31/2023',
    status: 'ACCEPTED',
    primary: '',
  },
  {
    severity: 'S2',
    note: 'This is acknowledged.\n',
    mentor: '',
    project: 'Background Work - Production KT',
    reviewer: '',
    priority: 'P2',
    type: 'epic',
    title:
      '[Parent Tracking Bug][Search Features][daas_request_responsiveness] For production pipelines KT',
    secondary: '',
    projectStatus: 'In-Progress',
    eta: '1/31/2023',
    vfOrg: 'NO',
    id: '265219473',
    assignee: 'apurvsharma',
    otd: '1/31/2023',
    primary: 'apurvsharma',
    status: 'ACCEPTED',
  },
  {
    severity: 'S2',
    note: 'This is acknowledged.\n',
    mentor: '',
    project: 'Background Work - Production KT',
    reviewer: '',
    type: 'epic',
    priority: 'P2',
    title:
      '[Parent Tracking Bug][Search Features][daas_request_responsiveness] For production pipelines KT',
    secondary: 'NA',
    projectStatus: 'In-Progress',
    eta: '1/31/2023',
    vfOrg: 'NO',
    assignee: 'apurvsharma',
    id: '265219473',
    otd: '1/31/2023',
    status: 'ACCEPTED',
    primary: '',
  },
  {
    severity: 'S2',
    note: 'This is acknowledged.\n',
    mentor: '',
    project: 'Background Work - Production KT',
    reviewer: 'rakshit',
    type: 'epic',
    title:
      '[Parent Tracking Bug][Search Features][daas_request_responsiveness] For production pipelines KT',
    priority: 'P2',
    secondary: '',
    projectStatus: 'In-Progress',
    eta: '1/31/2023',
    vfOrg: 'NO',
    id: '265219473',
    assignee: 'apurvsharma',
    otd: '1/31/2023',
    primary: '',
    status: 'ACCEPTED',
  },
  {
    severity: 'S2',
    note: 'This is acknowledged.\n',
    mentor: 'sayyadz',
    project: 'Background Work - Production KT',
    reviewer: '',
    priority: 'P2',
    type: 'epic',
    title:
      '[Parent Tracking Bug][Search Features][daas_request_responsiveness] For production pipelines KT',
    secondary: '',
    projectStatus: 'In-Progress',
    eta: '1/31/2023',
    vfOrg: 'NO',
    id: '265219473',
    assignee: 'apurvsharma',
    otd: '1/31/2023',
    primary: '',
    status: 'ACCEPTED',
  },
];

function dedup(data) {
  let results = [];
  const dedupData = data.map((item) => {
    let ids = [];
    if (!ids.includes(item.id)) {
      results.push(item);
    }
  });
  return results;
}
const ddata = dedup(data);
console.log(data.lenght);
console.log(ddata.lenght);
console.log(ddata);
